### ISSUE TITLE
Repair button

### ISSUE THREAD

**Issue by Quackers29** [TechStack/TS-RTS#104]
On all structures that have a semi destroyed state there could be a repair button that costs res and time to complete, ie brings a tower / wall / town hall back to full health,
Cost maybe half the initial price and 30 seconds.

**Comment by TechStack** [comment]
Repair has been suggested but i'm not sold on it. It introduces several mechanics that would need modifying in order to make it work.

**Comment by Czarified** [comment]
If repair is available, I think it's only necessary for the Town Hall. All other structures you can just build anew. I am also not sold on repair in general, but I definitely don't think it's needed on every structure.

**Comment by TechStack** [comment]
Not seeing a need for repairing .
