### ISSUE TITLE
No menu when rejoining during Start lobby

### ISSUE THREAD

**Issue by Quackers29** [TechStack/TS-RTS#126]

**Comment by Czarified** [comment]
I haven't seen this issue. Can you describe it in more detail? Is it easily repeatable? @TechStack made some changes to the lobby GUI today or yesterday.

**Comment by TechStack** [comment]
now that we can press "Y" key to go back to the lobby anytime the game is not running i'm closing this one down.
Use the "Y" key if you get stuck outside of the lobby
