### ISSUE TITLE
Need textures

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#151]
- [x] Research center block & builder item
- [x] Watch tower block & builder item
- [x] Wall block & builder item
- [x] Gate Block & builder item
- [x] Wall Steps & builder item

_CZ Edit: Fixing Markdown_

**Comment by Czarified** [comment]
a0c9b3652f42b4bd8e1493dc6e3eee3de619ac07
b52a07ab47e2814f1b97a198552ff63e7590c804
d3f3188270b92e13c02cfd3b07f9479767548ce5
c2a8978f45ae33dae44b779e6c7b2d69b7f0cdb7
7da342f828793ffab7253d734ceaf7ab043c1220
d19b8886c5b1e93dfe471dc5a6894da3a7ad96a8
2dfef6ecfe9d665d45a398084928a55ec8e7a0e4

Just the Research Center remaining.

**Comment by Czarified** [comment]
Commit 3be2c9076b6483bdf401c613f069156078afa820 added Research Center Textures. Closing this issue.
