### ISSUE TITLE
Pike Weapon

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#156]
Pike is small and actually looks like an axe. Need to scale up and possible translate more.

Some left-handed units also hold the pike completely weird.
![](https://cdn.discordapp.com/attachments/646148312793088021/655491572103643143/unknown.png)

**Comment by TechStack** [comment]
json updated for left hand usage in dev 
![image](https://user-images.githubusercontent.com/4016300/70918386-e56b9f80-1fec-11ea-9876-d351d4162972.png)

**Comment by Czarified** [comment]
pike size is still incorrect. See reference.
![Two_hoplites 1](https://user-images.githubusercontent.com/6953018/71381027-7ddac480-2597-11ea-91aa-141af0d1fea0.jpg)
