### ISSUE TITLE
ReadMe Update and Wiki

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#166]
Readme has never been updated, and an initial wiki must be created for ease of use.

I will be learning a web development framework for other side projects, so will attempt to use RTSCraft as my case study. Fall back option is the Github Wiki.

- [x] Readme.md update with basic information

- [x] Initial Wiki creation with basic pages beyond the readme.

**Comment by TechStack** [comment]
Note: When 1 unit is selected and pressing H if the player is sneaking it will select all Untis of that type.

**Comment by Czarified** [comment]
Basic wiki structure created. Still far off from complete documentation, but most of the pages are there and outlined.

**Comment by TechStack** [comment]
What pages, images etc. are needed to wrap this up for initial release?
I fully expect that over time we'll keep the wiki as a living document and enhance it well after release.

**Comment by Czarified** [comment]
I don't really have an idea for minimum viable product on the wiki. I started several pages and was going to try and write down full guides for everything, but I don't know what's really needed. What do you think? Maybe just record and video tutorial for release, and we'll add to the wiki as we go?

**Comment by TechStack** [comment]
Ok so sounds like it's not a show stopper. Just trying to get a grasp on what's left before initial release. Also was considering making a vid for each topic in the wiki.

**Comment by Czarified** [comment]
Initial information is there. Will expand as available. Closing.
