### ISSUE TITLE
Resource Production Structure Rates

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#167]
Currently, resource productions are not configurable, and only produce an additional 1 unit per game cycle. Changing these  will drastically change the gameplay, so they should at least be configurable.

- [x] Make Resource Production Configurable

- [x] Set production rates to initial values for playtesting

- [ ] Check balance with structure and unit costs

**Comment by Czarified** [comment]
Looks like this was an easy fix? I don't know if I'll have time tonight to do any balance testing. Maybe fiery or gazer can join you to check the costs. I imagine most things will need to be increased, now that we drastically changed the rates.

**Comment by Czarified** [comment]
Production rate defaults are probably still too high... Balancing will be nearly impossible before research and siege are implemented. For example, current rates may be fine, but structure and unit costs just need slight buffs.

We may want to move this to initial release instead of Beta v2.

**Comment by TechStack** [comment]
agree moving to intial release milestone

**Comment by TechStack** [comment]
Resource generation generally feels good for the greenfields map.
