### ISSUE TITLE
Building protection area around town hall

### ISSUE THREAD

**Issue by Quackers29** [TechStack/TS-RTS#205]

**Comment by Czarified** [comment]
What does this mean? Could you add a description please? I assume it's something you guys ran into on stream? Do you want to keep the players from breaking and placing blocks around the town hall, or keep a player from placing a wall or other building inside their town hall, or keep enemies from placing barracks directly outside your own town hall? There's many things this title could be referring to.

**Comment by TechStack** [comment]
I know whats up here. 
Its about preventing players from placing down structures inside an enemy base. We've had too many times where someone solo rushes in with 10 barrack blocks in hand and places them next to a town hall.
I'll probably resolve this one by enforcing an area of influence mechanic where you can only place buildings within your area of influence ..
Most buildings could have a 32x32 area of influence but something like the town hall may have a larger one to allow for resource gathering to be a bit further away in early game. 

So this new mechanic would slowly grow your area of influence from one building to the next allowing you to build anywhere in the map as long as they are connected to your town hall thru each others(buildings) area of influence .

games like they are billions use this concept but typically call it something like electrical power and use poles/ pillions to allow for it.

Again a config option to enable /disable to taste is probably good

**Comment by Czarified** [comment]
This makes complete sense to me. I always thought that the barracks were just too cheap, but even if we made them really expensive, one could still use this tactic quite effectively in late game.

What about a FOB (Forward Operating Base)? Since some maps are/will be large, it is understandable to create a FOB. Perhaps this is solved by just stringing farms (or watchtowers/walls) along in the direction of your FOB?

**Comment by Quackers29** [comment]
I still like the idea of (although this is a lot of work in total):
a single zone of protection for just the town hall (Main priority)
combined with a vunerable building time for military buildings (Secondary)
and a map to show directions of enemy attackers (Low priority)

Take AoE, no pillons there, just build time and an overview of the battle..

Also could increase the build time to train units

**Comment by TechStack** [comment]
Closing this as Area of influence mechanic was introduced. This will stop the cheese tatics of placing barracks beside an enemy townhall unless the team first increases its area of influence all the way over to the enemy townhall.
So it would be possible to build one next to the enemey townhall but will be hard to pull of as you must be building all the way to the enemey Townhall first ... and if you are strong enough to keep your buildings in alive all across the map to the Townhall then you are winning the game already anyway
