### ISSUE TITLE
Pikemen Nerf or Rebalance

### ISSUE THREAD

**Issue by TheOtherGuy110** [TechStack/TS-RTS#212]
Pikemen either need to be higher cost (e.g. have a diamond cost) or need a nerf. Too easy to construct a large army of them in comparison a high cost unit like an advanced knight, who gets absolutely demolished by them.

**Comment by Czarified** [comment]
Kind of a repeat of #209

**Comment by TechStack** [comment]
closing this one as it is a duplicate and will be addressed in #209
