### ISSUE TITLE
Watchtower Cost

### ISSUE THREAD

**Issue by TheOtherGuy110** [TechStack/TS-RTS#213]
The 1000 gold and 1000 diamond are simply unattainable on some maps. I understand the lag of them, but could there be a building cap of say, 2 towers? It’d be nice to try them out, especially with the recent lag optimizations.

**Comment by TechStack** [comment]
Agree they are too expensive but this is a config option and intended for now until as they can cause a high amount of lag in large numbers.

We'll get around to correcting it but need to understand why they lag first so it can be corrected.

**Comment by Czarified** [comment]
It doesn't seem like watchtowers lag anymore. Just need to update the defaults in the mod to values we've used on the server config before.

**Comment by TheOtherGuy110** [comment]
We can even play by honor and avoid spamming many of them in testing so we dont bog down the tps if its an issue

**Comment by TechStack** [comment]
Cost re-adjusted on the test server but subject to change still as we balance the game defaults overall.
