### ISSUE TITLE
Marketplace Structure, Texture, and Mechanics

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#215]
Marketplace to be implemented. The marketplace allows a player to trade excess resources for emeralds, which can then be used to purchase resources he/she needs. Resource trades are NOT P2P, and happen instantaneously.

- [x] Basic marketplace mechanics (static exchange rates)
- [x] Block needed
- [x] Builder Item needed
- [x] Dynamic exchange rates
- [x] Marketplace control block texture
- [x] Marketplace blockstate, model, and item JSON files
- [x] Basic Marketplace structure, for each team, with a pristine and ruined state (no tribal variants necessary)
- [x]  Marketplace GUI

**Comment by TechStack** [comment]
moving to post release
