### ISSUE TITLE
Population Cap - 3 Phases

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#221]
- [x] phase one - server level config only divided among playing teams

CONFIG_SERVER_MAX_TROOPS=1,000
2 teams
500 troops MAX per team
4(teams) = 250 troops per team

-----

- [ ] phase Two - Lobby players can choose to change settings below server cap 

CONFIG_SERVER_MAX_TROOPS=1,000
Lobby setting 500 0 thru SERVER MAX
-----------
CONFIG_SERVER_MAX_TROOPS=1,000
Lobby setting 500 0 thru SERVER MAX

HOUSES
each house = X population for a team

- [ ] phase Three -  House based pop cap... max cap set by server & lobby setting but cap starts at baseline and raises to the max cap as houses are placed in the world.

HOUSE =25 population 
4 = 100 population.

**Comment by Czarified** [comment]
Houses would require a new, tribal-themed structure. I'd definitely classify that as beyond Initial Release candidate. Would phase 2 also be post-release?

**Comment by Czarified** [comment]
Will make another issue for Phase 3, so we can assign it to a new milestone.

**Comment by TechStack** [comment]
all remaining parts are post release moving as such

**Comment by TechStack** [comment]
I'm not sure phase 2 & 3 of the population cap are still needed. 
The server based pop cap has been working well so far.
I may close this unless someone else strongly thinks they are needed.

**Comment by Czarified** [comment]
I think the server cap works well. Sometimes I wish I could push to get a larger army, but I think that whole concept is more complicated than what it would be worth. I'm fine with closing this. Focus on other aspects.
