### ISSUE TITLE
Units attempt to path find through water and drown.

### ISSUE THREAD

**Issue by TheOtherGuy110** [TechStack/TS-RTS#224]
I don't know what conditions they do it under, although they seemed more prone to pathing through water when told to attack a specific unit (command wand) rather than path to a certain area. Not a big deal, can be fixed with walls/fences. I'll try to see what circumstances they do it under this evening.

**Comment by TechStack** [comment]
Thank you for opening this. I had forgotten about it ;)

**Comment by TheOtherGuy110** [comment]
Played around with it more this evening - Units try to pathfind through the water under all circumstances. Doesn't matter if I target a specific unit or location. They're finding it as the shortest path.
