### ISSUE TITLE
Unit Training Queues

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#24]
Barracks and Archery range (and eventually Stables) should have the ability to control how many units are being trained at a time.

1. Initially, this should be implemented by adding a "Halt Training" button to the control block GUI. If not activated, the structure will continuously spawn a unit as long as resources are available.

2. Final implementation should allow flexibility to train different types of units at different structures, either continuously or a discrete amount.

3. It would also be beneficial to the playability to have an item/gui which can control training remotely.

**Comment by Czarified** [comment]
[https://lh3.googleusercontent.com/Mv3KwHnWZ7jT6-uoe6PS4uiprXX3bVPN99djwIAm4cFdCi98ovUhpBJIEgdjTANEr-HnidzO7WF7M8sYWFhQCL7XyxLkYhRlTfrUdbrIVJ0_W4-KhhSosYwviRjZ4tjuIoGLHAxFDGra5DujSqu3gPQw1kK--M4uteFjRY-rbtBcoIwteQDLiwuuQhhEmBd-El-9a1qOhSisHoPz3ZVU7zFFZURyF1yb5iw22Ea3tCrMNNJExfyqjUdnFty3MxFuk4Ff7UKJazEPYhZgaK1nTjjm-jmuP8aeHjekKmx6jsMa-dRsDRPegooDRQAveLV3LpMOj1XRI18L5s6NCPtlKjHRlCmmxHcd6r0nd-L7amXtBA04gCkBPbxUWV1kUqKBmBtfQy5EPKrQxortiGqT5SicBA0P2ILqJmoWkeJMqvboGIMFnVZKDyUlEBDVDqEIsWR79IgHSBAgWhsyibiWbetmZ-mhXdyJWTr6FZ58urQHuORXZFdpzDX7WBGzHYP3NIPvcK0itiHJsGurhVRxWPjMsbd8FB5798uXZ-Qhz0qUAOZXZmPv1P5lpPqc_5KE7VAXK2sh1lu3GoD5pq7-UvaLGmQ9lmCb2jcPZ4lTTHPXHaIYFMziGbmHYeZ-QByj2OxAEhrmz3BXsgHJmkrluG2LursGTFpvcLM51n7J0Irq6h-hDIlntC0=w970-h1293-no](url)

**Comment by Czarified** [comment]
![IMG_20191117_001624](https://user-images.githubusercontent.com/6953018/69003965-938e0780-08d0-11ea-9eed-0ad0c979fe18.jpg)

**Comment by TechStack** [comment]
Part 1 is implemented

**Comment by Czarified** [comment]
Do you think you'll be able to put a rudimentary GUI in for Beta1? I'm thinking it should default to not spawn them, and have a value of 0. You can decrement that to -1 to spawn infinite after you hit the checkbox. At that point, it's functionally the same as the current version, but we are working in the architecture for the final version.

**Comment by Czarified** [comment]
![IMG_20191120_111459](https://user-images.githubusercontent.com/6953018/69261415-1f30be00-0b87-11ea-9ec7-161378a55ef6.jpg)

**Comment by TechStack** [comment]
I think a next step should be to model the Gui Layout for the Town Center similar to this so we can know the cost of the buildings in testing runs.
Also having costing for the units would be nice as well but setting this up without the full queues would just mean re-writing it later.

I'm also trying to consider how chunk loading will impact the queues.
If a structure is "ON" and not loaded it cant spawn things in the current setup.

**Comment by TechStack** [comment]
unit Queues are in game now. 
Any further work will be pending play testing and most likely would be around the GUI for recruiting units.

**Comment by Czarified** [comment]
GUI works well. It is noteworthy that you can buy units without meeting the requirements for them. Resources are taken at time of purchase.

I think we need to implement an "infinite recruit" button some way.
