### ISSUE TITLE
Balanced Economy

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#27]
Initial values for production rates, and structure and unit costs have been estimated, but they are far from perfectly balanced.

Production rates, structure costs, and unit costs should all be changed based on iterative play testing. These values are open to modify in the configs, for rapid iteration. 

Initial play-testing seems to indicate that food rates should be buffed.

**Comment by Czarified** [comment]
Resources are shared between all players in Build 12. Hashmap features seem to be broken.

**Comment by TechStack** [comment]
Resource sharing component of this is resolved.

**Comment by Czarified** [comment]
Initial Economy has reached a stable state for gameplay. Game stat tools have been created to analyze economy and resource supplies for continued checks.

Closing issue.
