### ISSUE TITLE
Config Structure

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#28]
I don't know if it's possible, but it may be a lot easier to modify rates and costs in the config if things were structures in a list/array like they are in the spreadsheet.

So instead of a line for each value, have a line for each structure with the value: 

```
farmblock_costs = [int crop, int wood, int stone, int iron, int gold, int diamond, int emerald]

farmblock_production = [int crop, int wood, int stone, int iron, int gold, int diamond, int emerald]
```
So the total for the same block comes down to 2 lines instead of 14 (or whatever it is now. It looked very long on stream last night).

**Comment by TechStack** [comment]
Note on possible way to achieve this:
Use a config of type string and use the string split function to chop it into its composite parts.
Example: 
configNameLumberYardCost = "10,10,10,2,0,0"
Where each of the resource amounts are separated by a comma and in an ordered sequence 
@Czarified is this the type of simplification you are looking for?

Pros:
*  1 line per cost entry

Cons:
* More complex to code for but should be a one time setup.
* Could simplify use of the configs in other places
* Error handling complexities and would need feedback back to user via exceptions if they forget a resource value etc...
* no baked in way to enforce a range

**Comment by TechStack** [comment]
Confirmed this is possible to do on the Entity attributes.
Will still need to migrate the other settings to use this methodology. Keeping issue open until that is completed .
