### ISSUE TITLE
Unit Health To be pulled from configs

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#34]

**Comment by Czarified** [comment]
Currently, unit classes do not define unit health. It is inherited from vanilla MonsterEntity (I think). I cannot confirm exact syntax or source of value without forge dev set up. Once the class has health definition, we can add a line in the config for it.

It may be beneficial to break off unit stats into a separate config.

Sidenote: It is probably a good idea to define any other values of interest that are still inherited. Not sure what these would be right now, since I don't have the class code in front of me.

**Comment by TechStack** [comment]
Attributes I've uncovered so far:

- SharedMonsterAttributes.FOLLOW_RANGE
- SharedMonsterAttributes.MOVEMENT_SPEED
- SharedMonsterAttributes.ATTACK_DAMAGE
- SharedMonsterAttributes.ARMOR
- SharedMonsterAttributes.ATTACK_KNOCKBACK
- SharedMonsterAttributes.MAX_HEALTH
- SharedMonsterAttributes.KNOCKBACK_RESISTANCE
- SharedMonsterAttributes.ARMOR_TOUGHNESS
- LivingEntity.SWIM_SPEED
- LivingEntity.NAMETAG_DISTANCE
- LivingEntity.ENTITY_GRAVITY


Some of these we may not want to modify like ENTITY_GRAVITY and NAMETAG_DISTANCE for example

**Comment by Czarified** [comment]
Is the MAX_HEALTH given in half-hearts? So a player has 20 units of health?

**Comment by TechStack** [comment]
Created some simple debug code to extract all attributes on the Minion and the values currently in use. Results are here:

- ATTRIBUTES ARE SET AT :generic.maxHealth VALUE: 20.0
- ATTRIBUTES ARE SET AT :generic.knockbackResistance VALUE: 0.0
- ATTRIBUTES ARE SET AT :generic.movementSpeed VALUE: 0.23000000417232513
- ATTRIBUTES ARE SET AT :generic.armor VALUE: 2.0
- ATTRIBUTES ARE SET AT :generic.armorToughness VALUE: 0.0
- ATTRIBUTES ARE SET AT :forge.swimSpeed VALUE: 1.0
- ATTRIBUTES ARE SET AT :forge.nameTagDistance VALUE: 64.0
- ATTRIBUTES ARE SET AT :forge.entity_gravity VALUE: 0.08
- ATTRIBUTES ARE SET AT :generic.followRange VALUE: 35.0
- ATTRIBUTES ARE SET AT :generic.attackKnockback VALUE: 0.0
- ATTRIBUTES ARE SET AT :generic.attackDamage VALUE: 3.0
------------------------

Code if we ever need it again as it will not be part of the final mod:
```
	AbstractAttributeMap aam = this.getAttributes();
		Collection<IAttributeInstance> c = aam.getAllAttributes();
		for (Iterator iterator = c.iterator(); iterator.hasNext();) {
			IAttributeInstance iAttributeInstance = (IAttributeInstance) iterator.next();
			TSRTS.LOGGER.info("ATTRIBUTES ARE SET AT :" + iAttributeInstance.getAttribute().getName() + " VALUE: " + iAttributeInstance.getBaseValue());

		}
```
