### ISSUE TITLE
Armory

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#38]

**Comment by TechStack** [comment]
This is needed to add more unit types (with armor) so need it in Beta v2

**Comment by TechStack** [comment]
armory block is added need structure

**Comment by Czarified** [comment]
structure captured in issue #29 . Only texturing remains for this issue, then it can be closed.

**Comment by TechStack** [comment]
Close this now?

**Comment by Czarified** [comment]
This should have closed when you merged my branch in with master...did it not?

**Comment by TechStack** [comment]
no i'll close it now
