### ISSUE TITLE
Resource Storage

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#39]

**Comment by Czarified** [comment]
Resources, once gathered, must be stored somewhere. Each resource doesn't represent a physical block or item in the game. It is more of a currency, available to you as the player. Initially, your Town Hall has a very small capacity for storage, but this will need to be expanded with Resource Storage Control Points. Most resources will be stored in a Warehouse. Crops and treasure, however, will be stored in the Granary and Treasury. Resource Storage Control Points require resources and time to build, and you can build however many you see fit. Each one has unique costs and capacities, dependent on it's level.

**Comment by Czarified** [comment]
Closing for now. May investigate in the future if it seems to be a meaningful addition to gameplay.
