### ISSUE TITLE
Each Minion Type should have its own unique texture.

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#67]
While we currently have different textures for each team. Different Unit types should also get their own textures.
Example: Archers should appear different than Melee minions of the same team.
it helps to quickly distinguish between the unit types and adds to the game-play experience

**Comment by Czarified** [comment]
Initial unit textures will be slightly different. The goal would be enough to immediately distinguish, but similar enough that team is obvious.

Issue #32 will help with this.
