### ISSUE TITLE
Saving game stats.

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#70]
It's been determined it would be good to have some game stats saved periodically to a file so we can processes the data outside of Minecraft & visualize it via charts.

Data points to save:
* Economy : 
     -  Increase of each resource type.
     -  Total of each resource type.
* Army:
     - Counts of units by type.

* Building / Structures
     - Count of buildings by building type.

It has been determined that saving this once every RTS tick (currently defined as once every 10 seconds) should suffice and provide more than enough granularity for mapping the data out.
It is also the unit of time used to gain additional resources.

The processing of this data will be contained outside of the Minecraft mod itself but will likely be open source as well & shared in either this or a separate repo.

_CZ Edit: Fixing markdown._

**Comment by Czarified** [comment]
Do we want this to be a general issue related to gamestats, or just the export of them?

**Comment by TechStack** [comment]
I think a general issue as I need to capture the stats to be able to export them and just capturing without the export (writing to logfile) isn't useful so both needs to be done. Logging is simple anyway once they are captured.

**Comment by Czarified** [comment]
Current logging structure works well for reading data into python. Functions created that can easily create resource plots for any team, and save them as images. 

![Graph](https://i.imgur.com/jCA8zak.png)

**Comment by Czarified** [comment]
Still need unit counts and structure counts. With the new Unit Queue system, it may be easier to implement unit count and type logging, now?

**Comment by Czarified** [comment]
Structure and Troops stats now included in log file.

Structure header and number of entries per line seems to indicate duplicates in the logging.

**Comment by TechStack** [comment]
can this be closed now?
