### ISSUE TITLE
New Structure -Walls

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#93]

**Comment by TechStack** [comment]
added but need some work still

**Comment by Czarified** [comment]
Walls control block needs texture

**Comment by TechStack** [comment]
Wall needs to follow terrain and build on top of it properly .. could also use variable size ..
May need a different template building system for the wall to allow for all of its features

**Comment by Czarified** [comment]
Wall block palettes slightly modified to be more tribally distinctive.

**Comment by Czarified** [comment]
Walls work well is full-up playtest. May need to increase health slightly. Health balancing is a different issue. Closing this one.
